import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import "./globals.css";



const mona_Sans = Mona_Sans({
  variable: "--font-mono_sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="" lang="en">
       <head>
        <script src="/theme-toggle.js" />
      </head>
      <body
        className={`${mona_Sans.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
